### ISSUE TITLE
Logic condition.

### ISSUE THREAD

**Issue by KHYehor** [Kowalski0805/hunting#1]
`There is no case of last else condition. it breaks logic flow, doesn't it?`

https://github.com/Kowalski0805/hunting/blob/e0d351af4502b1ad162b204f4901545fcf6fdadc/Assets/Scripts/Animal.cs#L32

**Comment by Kowalski0805** [comment]
`AIState` is determined by 4 finite states (because it is an enum property), and with explicit conditions, it would be easier to notice that enum has been assigned unexpected value.

We do not expect any other value because we set it manually, but if there would be any bug that leads to that, I am not sure if final else statement will be any helpful.
